name: Deploy create-employee with Docker

on:
  push:
    branches: [main, qa]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Archive project files (excluding .git)
        run: |
          tar --exclude='.git' --warning=no-file-changed -czf create_employee.tar.gz . || true

      - name: Copy files to EC2 and deploy with Docker
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no create_employee.tar.gz ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            rm -rf /home/ubuntu/create_employee
            mkdir -p /home/ubuntu/create_employee
            tar -xzf /home/ubuntu/create_employee.tar.gz -C /home/ubuntu/create_employee
            rm /home/ubuntu/create_employee.tar.gz

            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update
              sudo apt install -y docker-ce
            fi

            sudo systemctl enable docker

            cd /home/ubuntu/create_employee
            sudo docker stop create_employee || true
            sudo docker rm create_employee || true
            sudo docker build -t create_employee .
            sudo docker run -d --restart always --name create_employee -p 8000:8000 --env-file .env create_employee
          EOF