name: Deploy create-employee with Docker

on:
  push:
    branches: [main, qa]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Archive project files
        run: |
          tar --exclude='.git' -czf create_employee.tar.gz .

      - name: Copy files to EC2 and deploy
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa create_employee.tar.gz ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            rm -rf /home/ubuntu/create_employee
            mkdir -p /home/ubuntu/create_employee
            tar -xzf /home/ubuntu/create_employee.tar.gz -C /home/ubuntu/create_employee
            rm /home/ubuntu/create_employee.tar.gz

            # Instalar Docker si no está
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y apt-transport-https ca-certificates curl software-properties-common gnupg
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update
              sudo apt install -y docker-ce
              sudo usermod -aG docker ubuntu
            fi

            cd /home/ubuntu/create_employee
            docker stop create_employee || true && docker rm create_employee || true
            docker build -t create_employee .
            docker run -d --name create_employee -p 8000:8000 --env-file .env create_employee
          EOF